### ISSUE TITLE
What will be the name of our project?

### ISSUE THREAD

**Issue by fkucuk** [SWE574-RenameMe/swe574-CoolName#1]
Naming is the most challenging issue that a software engineer can face ;) 

I remember sometimes deciding a name for a C# method could take much more time than coding its body. 

So, please write down your nominees. We can make a poll to elect one of them.

**Comment by TalatCikikci** [comment]
Here are some:

- "projectUlgen"
- "culturage"
- "culturall"
- "herital"
- "heriture"
- "sharitage"
- "heritago"

**Comment by yaseminalpay** [comment]
heritago looks good to me :)

**Comment by muatik** [comment]
I vote for heritago too

**Comment by sanal-cem** [comment]
Heritago is ok, many apps names are like Heritago, so Heritago would be a catchy name.

**Comment by tokonu** [comment]
+1 on heritago also domain is available

**Comment by sanal-cem** [comment]
I found heritago.us domain via https://www.namecheap.com for $0.88, seems very showy :)

**Comment by TalatCikikci** [comment]
![heritago](https://cloud.githubusercontent.com/assets/16108843/22824095/23ef5ba2-ef8f-11e6-8e45-9f71be68306e.jpg)

**Comment by kartalerkoc** [comment]
Heritago seems good.

**Comment by isik5** [comment]
Heritago or Culturage :+1:  :)

**Comment by fkucuk** [comment]
I think everyone agrees on **heritago**. 

It is settled then. **heritago** it is.
