### ISSUE TITLE
What will be the name of our group?

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#10]
Please write your attractive naming ideas to name our group. We should vote them using likes. Do not edit existing name comments. Start a new comment for any name you could find. We should like them. Unlikes would be exciting :)

**Comment by sanal-cem** [comment]
That would be attractive for youth.
* Jaijai ("Ceycay" in Turkish)

**Comment by sanal-cem** [comment]
Mr. Talat recommended "Groupago" and that brand new name accepted by most of the group.

**Comment by muatik** [comment]
So, one of the most difficult tasks has been completed then. 

![donalddraws1486973064379](https://cloud.githubusercontent.com/assets/106846/22875474/961a2300-f1d4-11e6-8790-40c76fa462dd.gif)

**Comment by yaseminalpay** [comment]
Groupago it is :)
