### ISSUE TITLE
DemoFormComponents.js

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#102]
DemoFormComponents.js file is included in the Material Admin Framework in static\assets\js\core\demo location. However, we need to edit that file for achieving working interactive elements like DatePicker or AutoComplete. #71 is also connected with that issue. From #71, only items given #demo-date, #demo-date-month, #demo-date-format, #demo-date-range, #demo-date-inline ids would work properly.

Is there any other way to pass that buggy issue which I didn't see, or should we change DemoFormComponents.js?

**Comment by sanal-cem** [comment]
I found a solution without changing any library file. I created some javascript functions in the external discover.js javascript file. These functions include wanted library codes and these functions could be changed in that way. The new javascript functions should be executed for every autocomplete or dropdown item after their creation.

**Comment by kartalerkoc** [comment]
Solved by peer-programming with @sanal-cem on 7 May 2017.
