### ISSUE TITLE
Any-Time DatePicker Opacity Problem

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#104]
- \#AnyTime--normDate, #AnyTime--startDate, #AnyTime--endDate are ids of three different AnyTime items which is generated via javascript. However, DatePicker could not appear without blur. Below css code works but does not solve that issue. Other date buttons above appear ahead.
```
\#AnyTime--normDate, #AnyTime--startDate, #AnyTime--endDate {
    opacity: 1;
}
```
- Below image shows the situation.
![image](https://cloud.githubusercontent.com/assets/6944468/25751351/5f69c2c4-31bd-11e7-954c-d5cfe7db79f7.png)

Unless elements are created via Javascript, they bring forward and block the DatePicker.

- Codes
HTML Code:
```
<div class="col-md-8">
	<form class="form">
		<div class="form-group control-width-normal">
			<div class="input-group date searchNoMargin demo-date">
				<div class="input-group-content">
					<input id="normDate" type="text" class="form-control">
					<label>Date</label>
				</div>
			</div>
		</div>
	</form>
</div>
```
JS Code:
```
AnyTime.picker( "normDate",
    {
        format: "%e %b %Y %E",
        formatUtcOffset: "%: (%@)",
        placement: "popup",
        baseYear: 2017,
        latest: new Date(2017, 04, 05)
    }
);
```
How could that issue solved?

**Comment by kartalerkoc** [comment]
Solved by peer-programming with @sanal-cem on 7 May 2017.

**Comment by sanal-cem** [comment]
When elements inside divs classes given input-group, these elements block the Any-Time DatePicker. Hence, ```<div class="input-group"> should be <div class="form-group">```
