### ISSUE TITLE
Which Programming Language Should We Use?

### ISSUE THREAD

**Issue by TalatCikikci** [SWE574-RenameMe/swe574-CoolName#11]
Ms. Uskudarli has presented us with two options to be used as the programming language for our project:

- Python
- Java

Which one do you think we should use?

Lets vote!

**Comment by TalatCikikci** [comment]
- Python

**Comment by TalatCikikci** [comment]
- Java

**Comment by fkucuk** [comment]
It's a good idea to decide it now :) Because I think I'll need to start tutorials in both cases, the sooner the better.

Unfortunately I've never used neither Java nor Python in my professional life. I've used Java just for the SWE573 project. I'd rather prefer Java because I cannot even spell "Python" before googling it ;)

But since there are lots of Python lovers and gurus in the team, it would be wise to choose Python, for the greater good.

**Comment by muatik** [comment]
Choosing the right tool depends on both requirements and the skills of team members. For instance, if we are going to develop, let's say, a more control and type-safe needed system, then java is a better choice than python. In python, we can be a bit lazy about controlling things, for instance, we would not care whether it's float or int, as long as it's numeric. If it's a banking system, then controlling everything tightly is inevitable.  

At the moment, even though the requirements are not clear; I sense that we are going to processes a lot of text data and for this kind of job, python is a wise choice. In addition, in our team, there are more people familiar with python than other languages. So I vote for python. 

are we now snake charmers?

![1_a](https://cloud.githubusercontent.com/assets/106846/22918149/86405180-f291-11e6-8dc6-58e0f07d76c1.png)

**Comment by TalatCikikci** [comment]
As someone who has tried using both Django and Spring before (I may still be wrong about some points);

#### Python + Django

|Pros|Cons|
|-----|-----|
| Easier to deploy and get into the actual project | Needs some extra configuration to make production ready (which is not necessarily the case in out project as we are not going commercial) |
| The official documents are very clear and updated | Some of the packages in the online repository ("pypi") are not available for the latest python releases (for example mysqlclient module) | 
| The language itself is very intuitive and easy to read, which is an advantage in group projects | |

#### Java + Spring

|Pros|Cons|
|-----|-----|
| A lot of resources can be found online for a lot of different cases | Half of the resources found online are outdated |
| Spring framework is very extensive and makes managing of a lot of features easy after you can master and configure it | Configuring and learning the spring framework is very cumbersome and hard |

This is what I can come up with at the moment feel free to edit this comment to add your pros and cons.

**Comment by fkucuk** [comment]
Is this for real? 
[25 OF THE MOST POPULAR PYTHON AND DJANGO WEBSITES](https://www.shuup.com/en/blog/25-of-the-most-popular-python-and-django-websites/) 

- YouTube
- DropBox
- SurveyMonkey
- Google
- Quora
- Reddit

...

**Comment by sanal-cem** [comment]
### Getting used to the intended environments
I would have initial development environment and configuration difficulties about Python and about different frameworks significantly. Getting used to a different framework might be harder than our expectations.
For example, self learning Spring framework with the knowledge of developing Java SE using the Eclipse environment had taken more than 20 times of time beyond my estimate. Moreover, I continued to use Eclipse IDE.
Therefore, in my opinion, before starting writing real codes, we need to discuss and share the future IDE, frameworks and configurations knowledge to initiate the project. As a note, IDE and frameworks should be agreed to be used.

**Comment by fkucuk** [comment]
If I was developing solo, I'd have rather preferred Java. Because I am much more familiar with it. But since this is a group project and I know there are several python gurus here who will support the newbies, I am voting for Python :)

**Comment by tokonu** [comment]
we decided to use python on backend and java on mobile
