### ISSUE TITLE
why is the heritage item detail page too narrow?

### ISSUE THREAD

**Issue by muatik** [SWE574-RenameMe/swe574-CoolName#111]
@kartalerkoc  @sanal-cem as you can see from the screenshot below, it is too narrow, are you planning to change it?
![image](https://cloud.githubusercontent.com/assets/106846/25809175/eb4a0c0a-3414-11e7-850d-e99d2769eb8a.png)

**Comment by kartalerkoc** [comment]
It was a design choice at the beginning, but it is not user friendly at the moment as heritage items can have long text descriptions. So, updated.

**Comment by muatik** [comment]
👍
