### ISSUE TITLE
Gather detailed info about heritage items

### ISSUE THREAD

**Issue by isik5** [SWE574-RenameMe/swe574-CoolName#115]

**Comment by kartalerkoc** [comment]
@isik5 Specific use cases include;
- "Nasrettin Hoca"
- "Göbeklitepe"
- "Baklava"
- "Mummy"
- "Santa Clause"

**Comment by isik5** [comment]
And we have also:

- Helva
- St. George
- Simit
- Thanksgiving Turkey
- Aşure
- Kapadokya
- Paintings which travels around the world.

**Comment by isik5** [comment]
Detailed info can be found at

 https://github.com/SWE574-Groupago/heritago/wiki/5.2-Use-Case-Examples
