### ISSUE TITLE
Preparing software design description document (SDD)

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#119]

**Comment by sanal-cem** [comment]
An editable SDD. The structure of this document follows the IEEE 1016 standard. https://docs.google.com/document/d/1_0_79recHgfqNEjn0-OxJQSebYAssgF3yqa7_JqHLyw/preview

**Comment by fkucuk** [comment]
Document is completed, as far as I know. No need to keep this issue open.
