### ISSUE TITLE
design a logo for the organization and the project

### ISSUE THREAD

**Issue by isik5** [SWE574-RenameMe/swe574-CoolName#12]
A logo is one of the most important artifacts that define an asset; just as a nation needs a flag, a team needs a logo. We should design a logo for our team and our project that would summarize our mission and vision, in a format that is usable both in the wiki and the application itself.

**Comment by isik5** [comment]
![heritago_log](https://cloud.githubusercontent.com/assets/8589660/22932944/e06f7a98-f2da-11e6-8483-65367c7eab0a.png)

**Comment by isik5** [comment]
![img_3426](https://cloud.githubusercontent.com/assets/8589660/23131550/1238a10a-f793-11e6-99c2-2d78906d1d82.PNG)

**Comment by kartalerkoc** [comment]
The second logo, with "HERITAGO" writing in brown color, seems appropriate as our **project logo** since we all agreed on Slack as well. Thanks to @isik5 for her contribution.

Next, we need a design for our **organization logo**.

**Comment by tokonu** [comment]
we have decided on isik's design
