### ISSUE TITLE
integration of heritage list view and API

### ISSUE THREAD

**Issue by muatik** [SWE574-RenameMe/swe574-CoolName#125]

**Comment by sanal-cem** [comment]
#### Did you solved CORS error on discover page?
- heritago/assets/js/discover.js file has changed within @muatik's commit related to that issue. However, when I'm trying to test it locally, it gives below error.
```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/api/v1/heritages?format=json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```
- info about my local environment: back-end works within docker from http://127.0.0.1:8000/ as suggested in [wiki](https://github.com/SWE574-Groupago/heritago/wiki/development) 
front-end works via webStorm. (webStorm starts the http://localhost:63343 server automatically.)
I posted a heritage item as below:
![image](https://cloud.githubusercontent.com/assets/6944468/26094092/30f0cfa2-3a21-11e7-86bf-09ab4c02b028.png)
so, it returns heritage data.
