### ISSUE TITLE
Prepare Mockups and add to Wiki

### ISSUE THREAD

**Issue by TalatCikikci** [SWE574-RenameMe/swe574-CoolName#13]
We should prepare mockups that capture our understanding of the system and present them to the customer. Getting feedbacks from the customer this way is important as it materializes out abstract image of the system, allowing each team member as well as the customer to have the same idea about the system. If we are able to prepare well designed mockups, we can agree on the system with least iterations possible and deliver an end product that meets the customer's requirements closely.

**Comment by isik5** [comment]
**Suggestions for Mockup tools:**

1) [Balsamiq Mockups](https://balsamiq.com/products/mockups/) 
2) [Mockingbird](https://gomockingbird.com/home)
3) [Mockup Builder](http://mockupbuilder.com/)
4) [MockFlow](http://mockflow.com/)
5) [HotGloo](https://www.hotgloo.com/)
6) [Invision](http://invisionapp.com/)
7) [Proto.io](http://proto.io/)
8) [Moqups](https://moqups.com/)

**Comment by sanal-cem** [comment]
Balsamiq Mockups accepted as most of the group members were used to use Balsamiq Mockups and Balsamiq Mockups provides to create a group project for creating mockups.

**Comment by tokonu** [comment]
should export mockups from mybalsamiq and add to wiki

**Comment by isik5** [comment]
UI Mockups are added to [Wiki](https://github.com/SWE574-Groupago/heritago/wiki/Mockups)
