### ISSUE TITLE
[My-Annotations-Page] should display text and image annotation

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#130]
Mockups created. If below muckups are applicable, mobile mockups will be created and all mockups will be posted to the mockups page in the wiki.
### My Annotations main page
![my_annotations](https://cloud.githubusercontent.com/assets/6944468/26243203/b8401f8e-3c93-11e7-910d-c7c3e98e6a3e.png)

### My Annotations text annotation
![my_annotations_text](https://cloud.githubusercontent.com/assets/6944468/26243220/c7697ef6-3c93-11e7-8307-86aef5d6e05a.png)

### My Annotations photo annotation
![my_annotations_photo](https://cloud.githubusercontent.com/assets/6944468/26243237/d1925eb6-3c93-11e7-8654-c9661b02f72e.png)

**Comment by kartalerkoc** [comment]
I think the designs in these mockups can be used. However, for now, our priority is to enable text annotation and image annotation functions first. Then, we can move on implementing my annotations page. Thanks for the designs @sanal-cem . Please add these mockups to [related Wiki page also](https://github.com/SWE574-Groupago/heritago/wiki/5.6-Mockups).

**Comment by sanal-cem** [comment]
My-Annotations-Page Web and Mobile mockups posted to wiki mockups page.
