### ISSUE TITLE
Research on Linked data platform - LDP

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#15]
- The Annotation Protocol provides a simple RESTful HTTP API for communicating among annotation clients and servers, and builds upon the Linked Data Platform specification. [link](http://w3c.github.io/web-annotation/admin/AnnoRecsPublished-BlogEntry.html)

- [This document](https://www.w3.org/TR/2014/NOTE-ldp-bp-20140828/) provides best practices and guidelines for implementing Linked Data Platform [LDP] servers and clients.

- To avoid the confusion about which datatypes could be used, LDPR representations should use only the following standard datatypes. RDF does not by itself define datatypes to be used for literal property values, therefore a set of standard datatypes based on [XMLSCHEMA11-2] and [RDF-PRIMER11] should be used.

### Useful links
https://www.w3.org/TR/2015/REC-ldp-20150226/
https://www.w3.org/TR/2015/NOTE-ldpatch-20150728/
https://www.w3.org/TR/2014/NOTE-ldp-bp-20140828/

**Comment by tokonu** [comment]
useful link about json-ld
http://json-ld.org

**Comment by sanal-cem** [comment]
### Useful information about JSON-LD
- To design domain-specific implementations, we could practice [interpret JSON as JSON-LD](https://www.w3.org/TR/json-ld/#interpreting-json-as-json-ld). This also means that we could create JSON-LDs using JSON with small changes.
- We must specify an [IRI](https://www.w3.org/TR/json-ld/#dfn-iri) to a valid JSON-LD document in an HTTP Link Header. Types and examples of [IRIs](https://www.w3.org/TR/json-ld/#iris)
- [IRI Expansion within a Context](https://www.w3.org/TR/json-ld/#iri-expansion-within-a-context) section provides easy understanding.
- [Aliasing keywords](https://www.w3.org/TR/json-ld/#aliasing-keywords) section explains utilizing JSON content.

**Comment by yaseminalpay** [comment]
#16
