### ISSUE TITLE
prepare use case diagrams and scenarios 

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#20]

**Comment by muatik** [comment]
According to the requirement document, we can create use-case diagrams as well as use-case scenarios to have a look at the requirements from another perspective. It also gives grouping related user actions together.

**Comment by yaseminalpay** [comment]
I have added the diagram to repo under diagrams/
Also gonna update use case scenarios in wiki.

**Comment by yaseminalpay** [comment]
updated the wiki.
