### ISSUE TITLE
try out a simple user acceptance test on creating heritage item and both image and text annotation on it.

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#216]
@muatik , I will try out the following steps and see if there will be a new issue or a failing step with the related operations;

- [x] 1. Create heritage item "Cappadocia"
- [x] 1.1 Add start date
- [x] 1.2 Add multiple origins
- [x] 1.3 Add multiple basic information key-value pairs
- [x] 1.4 Select "Polygon" map type for geo-location
- [x] 1.4.1 Add markers to build a hexagon area
- [x] 1.5 Add multiple images of Cappadocia
- [x] 1.6 Submit & create new heritage item "Cappadocia"
- [x] 2. Review data on the heritage item details page of Cappadocia
- [x] 2.1 Check if all the fields submitted in heritageForm also appears here correctly
- [x] 3. Annotate the description text of "Cappadocia"
- [x] 3.1 Add an annotation with motivation questioning
- [x] 3.2 Add an annotation with motivation linking
- [x] 4. Annotate the images of Cappadocia
- [x] 4.1 Use multiple shape selectors while annotating
- [x] 5. Check if total annotation number is incremented with addition of an annotation
- [x] 5.1 Check if total annotation number is incremented with text annotation
- [x] 5.2 Check if total annotation number is incremented with image annotation
- [x] 6. Refresh page to see if annotations made still exist

**Comment by kartalerkoc** [comment]
@muatik ,
2.1 is failing just because of missing date display, other data retrieved correctly
3.2 is failing as described in the image below in this issue

4. "Annotate the images of Cappadocia" is failing;
- As I click an image and the modal opens, I can select a rectangualer region with my mouse on the image before even clicking the start annotation button.
- When I click start annotation, select a region then click continue, the opening model displays the selected motivation and related input of the last annotation I made on the description of heritage item. The modal selection and input fields should be cleared when clicked to "Continue" button.
- When clicked to "Start Annotation" button, selected region and then clicked "Cancel" button next to "Continue" button, the selected region still displays

**Comment by kartalerkoc** [comment]
![cappadocia-user-acceptance-1](https://cloud.githubusercontent.com/assets/16115916/26528837/6c76285c-43bc-11e7-9637-d1595e62768d.jpg)
![cappadocia-user-acceptance-2](https://cloud.githubusercontent.com/assets/16115916/26528838/6c7ad7bc-43bc-11e7-9a93-10e3dbd7588d.jpg)
![cappadocia-user-acceptance-3](https://cloud.githubusercontent.com/assets/16115916/26528836/6c75904a-43bc-11e7-8ad6-97f85df9f339.jpg)

**Comment by isik5** [comment]
![text2](https://cloud.githubusercontent.com/assets/8589660/26529098/72638128-43c2-11e7-8205-8a41d0f40700.png)

Encountered the same issue with @kartalerkoc while trying to annotate an image. I can't able to type on the textual body

**Comment by muatik** [comment]
@isik5 this issue has been resolved but not deployed yet, @kartalerkoc confirm this please

**Comment by kartalerkoc** [comment]
@isik5 it is fixed locally, you can pull and test, but not at the deployment environment yet.

**Comment by isik5** [comment]
Comment annotations on images not listed 
![image ann](https://cloud.githubusercontent.com/assets/8589660/26529740/5ce407e4-43ce-11e7-9b62-cd8b184fd997.png)
![osman](https://cloud.githubusercontent.com/assets/8589660/26529741/5ce4cfda-43ce-11e7-9777-435bc08880c6.png)

**Comment by kartalerkoc** [comment]
Yep, I am working on it. @isik5

**Comment by kartalerkoc** [comment]
- Dates are now displayed.
- Basic information template, responsive design updated.
- Origin field template updated.

Waiting for back-end endpoint changes to display annotations related to that specific image on the modal @isik5 .
