### ISSUE TITLE
update project plan

### ISSUE THREAD

**Issue by tokonu** [SWE574-RenameMe/swe574-CoolName#23]
project plan should be updated based on the new issues

**Comment by tokonu** [comment]
I updated the project plan according to the newly created issues and milestones as we discussed on our meeting on 13.03.2017. Let me know if I missed something

**Comment by yaseminalpay** [comment]
i made some edits on the plan. switched use case and class diagram's dates. 
use case is not an architectural diagram but more related with requirements i think. 
closing the issue.
