### ISSUE TITLE
research libraries for android

### ISSUE THREAD

**Issue by tokonu** [SWE574-RenameMe/swe574-CoolName#27]
finding open source libraries that will help with the specific tasks will make the development faster and easier

**Comment by tokonu** [comment]
Authentication example using retrofit and okhttp https://futurestud.io/tutorials/android-basic-authentication-with-retrofit

**Comment by muatik** [comment]
We will also need an event bus manager not to dive right into the interface hell.

otto is a simple and sufficient library that I have experienced; and built by the company that also created OkHttp and Retrofit. http://square.github.io/otto/

**Comment by tokonu** [comment]
I assumed that there is a built in functionality for that in android as there is in ios but turns out there isn't. Otto seems good however I feel like using interfaces and delegates is a better practise https://www.youtube.com/watch?v=qDii69YCh_Q

**Comment by tokonu** [comment]
https://github.com/nostra13/Android-Universal-Image-Loader
i used this library for lazy image loading via http
