### ISSUE TITLE
Decide Frameworks for Frond-end pages

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#28]

**Comment by sanal-cem** [comment]
- [Material design project in byrushan.com](http://byrushan.com/projects/ma/1-7-1/jquery/light/) could be used as web systems' front-end framework.

**Comment by yaseminalpay** [comment]
i think we have decided this, going on with byrushan.

**Comment by kartalerkoc** [comment]
As we have encountered some problems related to dynamic elements that use Js in related material design, we are now working with [Bootstrap](http://getbootstrap.com/getting-started/) since we all have experience working with it in past.

**Comment by sanal-cem** [comment]
We could use [Bootstrap Material Design](http://rosskevin.github.io/bootstrap-material-design/) Seems as easy to use as Bootstrap. Briefly, general front-end development rules are same as Bootstrap. Only css changes are needed.

**Comment by sanal-cem** [comment]
Finally, we decided [MaterialAdmin Framework](http://www.codecovers.eu/materialadmin/pages/profile) for front-end development.
