### ISSUE TITLE
Decide a region/point selector library for images

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#29]

**Comment by sanal-cem** [comment]
Possible significant geometric image annotations:
- [Annotorious](https://annotorious.github.io/demos.html)
- [polyClip.js](http://www.useragentman.com/blog/2011/10/29/clipping-jpeg-images-into-non-rectangular-polygons-using-polyclip-js/)
- [p5*js drawing](https://p5js.org/examples/hello-p5-drawing.html)
- [two.js - two-dimensional drawing api](https://two.js.org/)
- [jsdraw2d](http://jsdraw2d.jsfiction.com/demo/circleellipse.htm)
- [gojs freehand drawing](https://gojs.net/latest/extensions/FreehandDrawing.html)
- [gojs SectorReshaping](https://gojs.net/latest/extensions/SectorReshaping.html)
- [gojs GeometryReshaping](https://gojs.net/latest/extensions/GeometryReshaping.html)

**Comment by muatik** [comment]
we need a similar library to use in the native android app. So far, we haven't come across anything that fits. That's why we are considering that we can use a webview to execute javascript in the native environment.  Executing js in android and accessing android libraries in js is easy as explained here: https://developer.android.com/guide/webapps/webview.html

**Comment by sanal-cem** [comment]
Annotorious is very buggy and it provides only point, polygon, box and freehand annotation all together on an image. [The all together package](https://github.com/annotorious/annotorious-selector-pack) has some bugs and could not executed directly. [OKFN Annotator Plug-Out example](https://annotorious.github.io/demos/okfn-plugout.html) couldn't be executed directly too. Furthermore, Annotorious does not have circle annotation.

**Comment by sanal-cem** [comment]
[GOJS](https://gojs.net) provides every tool for image annotation, however it also requires much integration between different annotation types. Therefore, many javascript and GOJS codes should be written to use GOJS for annotating images.

**Comment by sanal-cem** [comment]
[Djaodjin jQuery plugin](https://djaodjin.com/blog/jquery-plugin-to-annotate-images.blog) seems very proper for immage annotations. Seemingly, it only requires fetching fromx, fromy, tox, toy, points, currentWidth, currentHeight, etc. variables from djaodjin source javascript code. Moreover, different triangular shapes could be drawn via arrows.

**Comment by sanal-cem** [comment]
- Finally, everything needed for annotating images included in [VGG Image Annotator (VIA)](http://www.robots.ox.ac.uk/~vgg/software/via/)  Below example executed locally shows that VGG Image Annotator project has rectangle, ciecle, ellipse, polygon and point annotation with JSON outputs (The module could give JSON outputs with only a click.) Moreover, only javascript is used to build that module. No external javascript libraries! I prayed that they had not become blind after developing that module.
![vga_oxford_annot](https://cloud.githubusercontent.com/assets/6944468/24831759/00ddceea-1ca9-11e7-88d0-18edca02db57.png)
- JSON output of annotations:
```
{"ford-mustang-1967-fastback-i7.jpg584510":{"fileref":"","size":584510,"filename":"ford-mustang-1967-fastback-i7.jpg","base64_img_data":"","file_attributes":{},"regions":{"0":{"shape_attributes":{"name":"circle","cx":417,"cy":673,"r":41},"region_attributes":{"name":"Symbol"}},"1":{"shape_attributes":{"name":"ellipse","cx":1322,"cy":1139,"rx":273,"ry":47},"region_attributes":{"name":"Mustang logo"}},"2":{"shape_attributes":{"name":"rect","x":1083,"y":453,"width":188,"height":137},"region_attributes":{"name":"window"}},"3":{"shape_attributes":{"name":"point","cx":780,"cy":481},"region_attributes":{"name":"point"}}}}}
```
- However, there would be a disadvantage. Integrating VGG Image Annotator into the Display-Image-Annotations page would be a huge struggle.

**Comment by sanal-cem** [comment]
[VGG Image Annotator (VIA)](http://www.robots.ox.ac.uk/~vgg/software/via/) has a [documentation](https://gitlab.com/vgg/via/blob/master/CodeDoc.md) page. However, [VGG Image Annotator (VIA)](http://www.robots.ox.ac.uk/~vgg/software/via/) source code is understandable and documentation do not provide sufficient support.

**Comment by muatik** [comment]
I did a brief research in the source code of VGG. I think we can modify it for our purposes. If it is ok for you, I can take this take.

**Comment by sanal-cem** [comment]
Yes, you can develop VGG.
