### ISSUE TITLE
Research dummy server for JSON response on front-end implementation

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#30]

**Comment by muatik** [comment]
As stated here https://github.com/SWE574-Groupago/heritago/issues/26#issuecomment-288968234, you could have a look at JSON server or the api bluprint project.

### Get a full fake REST API with zero coding in less than 30 seconds (seriously)
https://github.com/typicode/json-server

**Comment by muatik** [comment]
@tokonu did you find the API blueprint useful? Can we send a http requests to get a JSON response? If so, we can run it on an ec2 instance so everybody can access it and consume it without doing anything in local development environments.

**Comment by tokonu** [comment]
The cool thing about it is that it is written in markdown so looks good when viewed in github we do not need to write a separate documentation. When the server is run it responds with the predetermined json to the requests made to the specified endpoints. So it should be useful for frontend development

**Comment by kartalerkoc** [comment]
Cool @tokonu ! Then we can simply start developing front-end by implementing our REST API through API Blueprint. Also, [this tutorial about polls](https://apiblueprint.org/documentation/tutorial.html) on their page is very easy to follow and understand the basics on how to use API Blueprint. Thanks for your suggestion @muatik .
