### ISSUE TITLE
Environment configuration for front-end development

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#31]

**Comment by muatik** [comment]
You can store front-end work in the directory `heritago/static` so we can serve them via Django backend app without the need of another HTTP server.

**Comment by muatik** [comment]
@sanal-cem @kartalerkoc @yaseminalpay what do you think?

**Comment by kartalerkoc** [comment]
@muatik Exactly. It makes sense to store templates, javascript files and static files such as images under `heritago/static` just as in the previous semester's Django projects.

**Comment by yaseminalpay** [comment]
i think we're good to go.
will use webstorm.
base template is byrushan.

for now we will continue going with implementing templates regarding to mockups.
we can push to repo under /static when we finish our work.
