### ISSUE TITLE
Decide on Tools to be Used in the Project

### ISSUE THREAD

**Issue by TalatCikikci** [SWE574-RenameMe/swe574-CoolName#4]
As we are working in a team, it is important that we standardize the tools that we use, so that any output we create is easily interchangeable between each other.

In general , following is a list of categories for which we should find tools for:
- [ ] Code Quality
- [ ] Time Tracking
- [x] Continuous Integration
- [x] Update Notifications
- [x] Versioning (GitHub as the repository, but what should we use locally? GitHub Desktop? Cmd?)
- [x] Dependency Management
- [x] Documentation
- [x] Project Planning
- [x] Task Management
- [ ] UML Editor
- [x] Mockup Editor
- [x] IDE
- [x] Intra-Team Communication

Please reply with possible candidates for each category, and we can decide upon the tool to be used by voting.

**Comment by muatik** [comment]
My candidates are as follows:
- code quality: #3, and coding standards which depend on tech stack
- Time tracking: toggle
- CI: travis-ci.org, and maybe github webhooks for automatic deployments.
- Dependency management: depends on tech stack
- documentation: github wiki
- Task management: github issues, milestones and projects sections?
- IDE: depends on tech stack
- Intra-team communication: for free talk, slack or gitter.

**Comment by isik5** [comment]
[ZenHub](https://www.zenhub.com/) for Task Management

**Comment by yaseminalpay** [comment]
We can use zenhub with harvest for tracking estimated and actual time. Easy to use and integrated with github.

**Comment by yaseminalpay** [comment]
Experience: we should never use GitHub wiki for project planning. Maintenance is a big issue.

**Comment by sanal-cem** [comment]
![image](https://cloud.githubusercontent.com/assets/6944468/22821509/14a2b5d2-ef84-11e6-8e50-2894a926a372.png)
A visual from ProjectLibre shows both my old project plan and Gannt chart. I like that tool but lets make a poll to decide a task management tool.

**Comment by TalatCikikci** [comment]
# I will update this comment to list the latest candidates before we vote


- **Code Quality - Codacy / Coveralls**
- Time Tracking - Toggl / Harvest
- **Continuous Integration - Travis CI / GitHub Webhooks**
- Update Notifications - E-mail/Slack
- **Versioning - GitHub / GitHub Desktop**
- Dependency Management - pip + requirements.txt
- **Documentation - MS Office / GitHub Wiki**
- Project Planning - MS Project / ProjectLibre / ganttpro.com
- **Task Management - GitHub Issues / ZenHub**
- UML editor - Visual Paradigm / UMLet
- **Mockup Editor - Ninja / Balsamiq**
- IDE - PyCharm
- **Intra-Team Communication - Slack / Whatsapp / Gitter / Doodle**

**Comment by tokonu** [comment]
i think it would be better to find an online tool for project plan. i used ganttpro.com for the previous project but the downside is you dont get a lot of features in the free plan

**Comment by yaseminalpay** [comment]
actually, that's true. it would be nice if every tool is online, so that anyone can view and edit.

**Comment by kartalerkoc** [comment]
Built-in "**Projects**" tab for **task management.** Easy to follow board and panels.
"**Balsamique Mockups**" as a **mockup editor**.
GitHub "**Wiki pages**" for **documentation** purposes.
"**Slack**" for **intra-team communication**.

**Comment by fkucuk** [comment]
**Time Tracking - Google Spreadsheets**

**Project Planning - MS Project / ProjectLibre / ganttpro.com**
MS Project is the best, but too expensive and there is no student licencing is available. 
ProjectLibre is good but not online option is available. 
ganttPro looks fine I guess. Free plan is more than enough for us I think.

**Task Management - GitHub Issues / ZenHub**
I prefer to use gitHub's cards (The Project tab), unless zenhub provides extra cool features. 

**UML editor - Visual Paradigm**
I like Visual Paradigm. But you need its application to use it. 
Has anyone used the tool mentioned by Suzan: UMLet?

**Mockup Editor** 
NinjaMock is free and good. If you have licence, balzamiq is fine also.

**IDE - TBD**
For compatibility issues, it is good practice for everyone to use the same IDE. 
JetBrains's tools rock.

**Intra-Team Communicaion - Slack / Whatsapp / Gitter**
If there is another tool that is integrated with github better than slack, we can give it a try. Remember Suzan's mentioning IRC integration with github for documenting the meetings. Or we can try to find a better slack <-> github integration tool. There has been lots of good discussions and decision makings on Slack, it would be good if we can report them to github with a tool.
I've examined the Gitter a bit, this morning. It has integration wit gihub, but as far as I examined it is not more than notifications.

**Comment by TalatCikikci** [comment]
Required tools are decided upon. Closing this issue for now.
