### ISSUE TITLE
create django models for annotation data models

### ISSUE THREAD

**Issue by muatik** [SWE574-RenameMe/swe574-CoolName#41]
We need Django models that cover all the annotation data models proposed in #16 

It is possible to create a single django model for all the annotations, or we come up with separated models derived from a base model class. But note that in django, single table inheritance is not possible.

In addition, if necessary, serializers for these models are also be done.

depends on #39

**Comment by TalatCikikci** [comment]
Models and serializers are ready to be reviewed and tested for annotation models.

**Comment by TalatCikikci** [comment]
Merges #155  and #177
