### ISSUE TITLE
Copying a whole Framework into local

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#44]
- Copying a website using browser mostly could not succeed. As all resources can't be downloaded via browser.
- Example: Material design framework copied from [link](http://byrushan.com/projects/ma/1-7-1/jquery/light/) via [HTTrack](https://www.httrack.com) software.

**Comment by muatik** [comment]
@sanal-cem the first approach, getting a framework by hard copying, is not the right thing. There must be a package including all necessary stuff for development environment. And there is.

**Comment by sanal-cem** [comment]
[Material Admin Responsive + AngularJs](https://wrapbootstrap.com/theme/material-admin-responsive-angularjs-WB011H985) seems to have necessary stuff for development environment. However, they don't have any trial licence or anything like trial to achieve that stuff. Hard copying the framework provides a trial environment. After hard copying,, we could decide to purchase that framework or research again for a more suitable framework.

**Comment by yaseminalpay** [comment]
we will not download, but use its components with links in html head.

**Comment by muatik** [comment]
using a template without obtaining its source code would cause a lot of problems in the "near" future. what is your strategy?

**Comment by sanal-cem** [comment]
We downloaded source code components and these components work locally, however static source calls would create problems. We are still thinking about that issue.
