### ISSUE TITLE
complete template for create heritage item page

### ISSUE THREAD

**Issue by yaseminalpay** [SWE574-RenameMe/swe574-CoolName#49]
complete template using byrushan as we spoke in meeting.
Template should be designed regarging to mockups

**Comment by kartalerkoc** [comment]
This issue is now under milestone [FE5 - Create-Heritage-Item-Page is ready.](https://github.com/SWE574-Groupago/heritago/milestone/16) @yaseminalpay

**Comment by kartalerkoc** [comment]
I have completed the initial template for [Create-Heritage-Item] page.
- Create Heritage Item template initiated.
- MaplaceJS introduced for Geolocation
- Drag and drop file uploader added
- Create_heritage_item.js file added
