### ISSUE TITLE
Research today's practicable projects about Cultural Heritage

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#5]
1. [World Heritage in India](https://play.google.com/store/apps/details?id=com.qizhi.worldheritagein), [World Heritage in Iran](https://play.google.com/store/apps/details?id=com.qizhi.worldheritageir), China, France, Japan etc. applications seems very proper for my software development technique. We would add different ideas to that application and develop a more usable and intriguing application. I documented World Heritage in India.

## Main Page
![image](https://cloud.githubusercontent.com/assets/6944468/22855974/7d0fbf3a-f091-11e6-8c9f-0881363006ad.png)
![image](https://cloud.githubusercontent.com/assets/6944468/22855977/85e85e64-f091-11e6-8606-9aa5815344ff.png)

## Information Page
![image](https://cloud.githubusercontent.com/assets/6944468/22856048/d59725c0-f092-11e6-9ba9-36a1f8d0d122.png)

## Information Page 2
![image](https://cloud.githubusercontent.com/assets/6944468/22856054/e734dd40-f092-11e6-9980-a5cf9cc5ab48.png)

## Photo Page
![image](https://cloud.githubusercontent.com/assets/6944468/22855981/a854881a-f091-11e6-852c-0a6b499ac0f7.png)

## Example Photo
![image](https://cloud.githubusercontent.com/assets/6944468/22855989/ed77ce3e-f091-11e6-9b1f-e0682436cb49.png)

## Countries Page
That page is like an advertisement, user should download each countries heritage application one by one. There are 25 countries!
![image](https://cloud.githubusercontent.com/assets/6944468/22856004/19319a64-f092-11e6-971c-c9d512fdeecd.png)

## Buggy map page
![image](https://cloud.githubusercontent.com/assets/6944468/22856019/533ae0da-f092-11e6-82b5-a48f6fc73ced.png)

## Advertisements
![image](https://cloud.githubusercontent.com/assets/6944468/22856078/3e6068d2-f093-11e6-9fb6-5954381c560b.png)

These small advertisements above would be enough to gain some profit from our future application. Moreover, we would find better and more attractive advertisements for our future application.

**Comment by tokonu** [comment]
we have researched the existing cultural heritage projects and gain knowledge about what to expect
