### ISSUE TITLE
Create Search-tab template

### ISSUE THREAD

**Issue by yaseminalpay** [SWE574-RenameMe/swe574-CoolName#50]
Prepare html template regarding to mockups

**Comment by sanal-cem** [comment]
First [Search page prototype](https://github.com/sanal-cem/heritago/tree/dev/static) is ready in sanal-cem's GitHub. It could be tested with json data using [JsonPlaceholder](https://jsonplaceholder.typicode.com) as described in #64.

**Comment by sanal-cem** [comment]
Search page visual prototype is ready. Source code stands in that [link](https://github.com/sanal-cem/heritago/tree/dev/static).

![image](https://cloud.githubusercontent.com/assets/6944468/25303794/b106e22a-2762-11e7-885d-abfbc70b8f1d.png)

![image](https://cloud.githubusercontent.com/assets/6944468/25303791/9b9e972a-2762-11e7-88c6-ca3c1a032f3e.png)

**Comment by sanal-cem** [comment]
New search page prototype.
![search_page](https://cloud.githubusercontent.com/assets/6944468/25490098/7d4c28a8-2b74-11e7-92d6-9a188ba02fb0.png)

**Comment by sanal-cem** [comment]
Advanced Search-tab and Search-tab templates are combined into Discover page.
