### ISSUE TITLE
Create portfolio page template

### ISSUE THREAD

**Issue by yaseminalpay** [SWE574-RenameMe/swe574-CoolName#51]
Prepare html template regarding to mockups

**Comment by sanal-cem** [comment]
Portfolio page prototype is ready.
![image](https://cloud.githubusercontent.com/assets/6944468/25332875/cf502a04-28f0-11e7-8717-431bd3570844.png)

**Comment by sanal-cem** [comment]
### Portfolio Page v2:
![portfolio](https://cloud.githubusercontent.com/assets/6944468/25680662/48b0ef1c-305a-11e7-8c1c-857b1ccf442f.png)

**Comment by sanal-cem** [comment]
### Final Portfolio page:
![portfolio](https://cloud.githubusercontent.com/assets/6944468/25819262/1b1825d6-3436-11e7-9916-db2dfec49c4f.png)
