### ISSUE TITLE
Create advanced Search-tab template

### ISSUE THREAD

**Issue by yaseminalpay** [SWE574-RenameMe/swe574-CoolName#52]
Regarding to mockups

**Comment by sanal-cem** [comment]
First [Advanced Search page prototype](https://github.com/sanal-cem/heritago/blob/dev/static/advSearch.html) is ready in sanal-cem's GitHub. It could be tested with json data using [JsonPlaceholder](https://jsonplaceholder.typicode.com) as described in #64.

![advanced search page](https://cloud.githubusercontent.com/assets/6944468/25306666/78891a48-279a-11e7-96dd-91130f359687.png)

**Comment by sanal-cem** [comment]
datepicker item has a problem. date could be written as "22.04.2017". Dates can't be chosen until the next commit.

**Comment by sanal-cem** [comment]
Could date be used as below? User should choose + or - and write a year, or day. e.g. user could write 5 as year or 12.12.5 as date.

![advanced_search_page](https://cloud.githubusercontent.com/assets/6944468/25488044/a19b4014-2b6e-11e7-8c96-5f7001620d4c.png)

Moreover, that usage would be proper to other pages.

**Comment by sanal-cem** [comment]
Advanced Search-tab and Search-tab templates are combined into Discover page.
