### ISSUE TITLE
write unittests for django models and views

### ISSUE THREAD

**Issue by muatik** [SWE574-RenameMe/swe574-CoolName#54]
We need unit tests for each django models and views. Because most of the work is carried out by the framework, we only need tests for custom model functions and behaviors.  However, we need to test views/endpoints to make sure they do not accept invalid data types etc. This is integration testing rather than unit testing

**Comment by fkucuk** [comment]
@muatik do you know or use or recommend an add-on  for documenting tests on django? Or shall we proceed with manual documenting?

**Comment by muatik** [comment]
Which kind of documentation?

**Comment by fkucuk** [comment]
with automated testing, a tool which generates a report like javadoc.

with a rough search I've found a tool named [Jenkins](https://sites.google.com/site/kmmbvnr/home/django-jenkins-tutorial). we can generate a report to add the SDD.

**Comment by fkucuk** [comment]
integration testing and backend programming will be coded in parallel.
100% of the current views' and models' testing is complete.

**Comment by fkucuk** [comment]
django's native test library and coverage library will be used.

for documentation, output of verbosity with degree 2 will be used.
