### ISSUE TITLE
REST API to delete given annotation

### ISSUE THREAD

**Issue by muatik** [SWE574-RenameMe/swe574-CoolName#59]
There is a need for an API to delete given annotations. It should simply require annotation id to be deleted.

`DELETE /heritages/1/annotations/9`
This request should delete the annotation whose id is 9, and belongs to the heritage item 1. The request body should be empty.

This is not documented on the wiki pages. It should be also done.

depends on #41

**Comment by TalatCikikci** [comment]
Django rest-api framework handles this. Tested and verified by @fkucuk .
