### ISSUE TITLE
Responsive bootstrap designs

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#65]
- As we are using bootstrap, our front page designs should be responsive for any screen size. Please read [Responsive Web Design - Introduction](https://www.w3schools.com/css/css_rwd_intro.asp) and examine examples for developing responsive pages.
- Inserting every class="col-" to every div and testing pages is an easy solution for designing responsive pages in bootstrap.
```<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">```
- For sure there are other issues to understand for creating responsive designs.

**Comment by kartalerkoc** [comment]
For basic grid layout: [Grid Template for Bootstrap](http://getbootstrap.com/examples/grid/)

**Comment by kartalerkoc** [comment]
We have decided and started implemeting "Material Admin" framework which is based on Bootstrap, so the same grid template for Bootstrap is being used on Web page templates now.
