### ISSUE TITLE
Private or Public GitHub Repo

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#7]
Do we really want others to see or c?py our labour?
Please like whichever you want.

**Comment by sanal-cem** [comment]
* Public

**Comment by sanal-cem** [comment]
* Private

**Comment by muatik** [comment]
I prefer public repos. Sharing is not bad, so all the tools and technologies we are going to use will be open sourced. They can come and look what we are doing, and learn from us to improve their repos. It looks fine to me. Copy&paste/stealing is another issue; if they do so, this is their problem, not ours.

**Comment by isik5** [comment]
Public +1

**Comment by kartalerkoc** [comment]
I used and learned a lot from open-source tools and projects. Thus, I would like to share what we do with the community even if it helps them a little bit.

**Comment by sanal-cem** [comment]
Actually, I wanted to mean that a private repo for 3 or 4 months would be a benefit for us. After 3 or 4 months, we would turn it to public and everyone could see the processes and the final project. However, as most members want a public project, it should be public certainly.
