### ISSUE TITLE
Datepicker problem on MaterialAdmin framework

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#71]
- Trying to insert datepicker items into advanced search page page caused me to find out buggy issue about datepicker item.
- https://github.com/SWE574-Groupago/heritago/blob/dev/static/html/forms/advanced.html contains datepicker item. When that page is executed, date showcase box should be opened:
![image](https://cloud.githubusercontent.com/assets/6944468/25306841/9524155a-279e-11e7-90db-401c1d1d166d.png)
- However, it can't be opened without adding code below:
```
<input type="text" id="autocomplete1" class="form-control hidden" data-source="html/forms/data/countries.json.html" placeholder="Countries">
```
Outer <div datepicker id should be given as '#demo-date', '#demo-date-month' or '#demo-date-format'. However, after giving '#demo-date' to id, only one datepicker could work. Hence, I had to change javascript source code by adding a class level change for that issue.
Datepicker code:
```
<div class="input-group date demo-date">
	<div class="input-group-content">
		<input type="text" class="form-control">
		<label>Datepicker</label>
	</div>
	<span class="input-group-addon"><i class="fa fa-calendar"></i></span>
</div>
```
Changed DemoFormComponents.js source code:
```
	p._initDatePicker = function () {
		if (!$.isFunction($.fn.datepicker)) {
			return;
		}
		$('.demo-date').datepicker({autoclose: true, todayHighlight: true});
		$('.demo-date-month').datepicker({autoclose: true, todayHighlight: true, minViewMode: 1});
		$('.demo-date-format').datepicker({autoclose: true, todayHighlight: true, format: "yyyy/mm/dd"});
		
		$('#demo-date').datepicker({autoclose: true, todayHighlight: true});
		$('#demo-date-month').datepicker({autoclose: true, todayHighlight: true, minViewMode: 1});
		$('#demo-date-format').datepicker({autoclose: true, todayHighlight: true, format: "yyyy/mm/dd"});
		$('#demo-date-range').datepicker({todayHighlight: true});
		$('#demo-date-inline').datepicker({todayHighlight: true});
	};
```

**Comment by kartalerkoc** [comment]
I have tried adding datepicker to another page just to test it out and it works fine. You just need to add following lines in your hmtl.

```
<script src="assets/js/libs/bootstrap-datepicker/bootstrap-datepicker.js"></script>
<script src="assets/js/core/demo/DemoFormComponents.js"></script>
```
