### ISSUE TITLE
Create a List of Probing Questions for Requirements Elicitation

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#8]
Please comment below your questions so that we can create a list of probing questions and document the final version of the list to its [related Wiki page](https://github.com/SWE574-RenameMe/heritago/wiki/Probing-Questions).

**Comment by sanal-cem** [comment]
## Questions about first requirements elicitation draft:
1. "The media files may exist on other platforms so long as the user has permission to share them. In other words, the wisdom of the crowds will also be recorded"???
What does it mean by "Other platforms" in the middle of the sentence above?

2. Could the sentence below is only an information sentence or is it about project development?
"The Web Annotation Data Model [2] describes the vocabulary and its characteristics."

3. What is the standard for annotations (23rd requirement on List of Requirements wiki)?
Should it be W3C standard?
How many types of annotations would exist?
Should annotations be done on pictures?
Should the user directed to heritago website for annotating images or should the user perform annotations on different sites?

4. How about retrieving information from the APIs? Would these information saved into the database of our project?

5. How about non-functional requirements? 
a. What would be the systems response time?
b. Should the system perform regular backups?
c. How secure the system should be?

5. Are these registration requirements applicable?
a. A Non-Registered user should be able to register the system.
b. Username for users' log in would be users e-mail.
c. Password for users' log in should exist.
d. The user should be logged in to the system with using his/her username and password.
e. The users’ password should be shown as masked password.
f. When the user forgets her/his password, s/he should recover it with his/her e-mail.
g. An e-mail to reset users’ password would be sent for password recovery.
h. The user should click the link inside the password recovery e-mail and change his/her password within the system.

## Notes:
1. Last paragraph of the Project Description should be thougt properly.

**Comment by fkucuk** [comment]
1- What is the main motive for this application?

- to earn money
- socialize people through cultural heritages
- make people share their thoughts, memories, knowledge about a heritage item
- a good implementation example for Web Annotation

_By this question we try to understand the customer’s main purpose, so we can focus on that
goal much more?_

2- Any other objectives mentioned other than question number 1?
_Maybe we are missing something._

3- The main structure for the system we think is ahead? Is it okay to build this kind of hierarchy?

![image](https://cloud.githubusercontent.com/assets/3140657/23115157/c1856898-f74b-11e6-894d-1f7d448878a6.png)

_Actually most of the customers do not understand the diagrams. But luckily we have an engineer customer here. We can use it. And this diagram tells a lot about the constraints the system we will build. For instance it requires users to create a "Heritage Item" to begin. Then adds "resources" to it, which may be in any kind of digital media. Annotations are built on resources. But the resources my be annotations themselves. And of course annotations can be annotated also._

4- Will there be a voting or reputation system? Every contribution made by users will be voted by other users. The higher reputation you have, the more privileges you got. Skipping the moderation for instance. Or more power on flagging an abuse.

5-  How about preventing abuse? Is a flagging system is okay? Where users flag an item as "abuse" and moderators will take the necessary actions. Deleting, editing the flagged content. Suspending the abuser's account. etc.

6- From the project description a Firefox add-on is described. The mobile application is not mentioned. What will be the scope of the mobile application? Of course they (the add-on and the mobile app) will use the same API we will build. Is it okay if the mobile app is limited for some features? For instance it will be hard for a user to annotate a video, or photograph. 

_(UX limitations)_

**Comment by tokonu** [comment]
1 - Is it okay to assume that all users will annotate in english or do we need to handle annotations in different languages
2- Assume that a person annotated a text in webpage A and another person annotated a text in webpage B, both about the heritage item X via the plugin. Will plugin users see both annotations in each website or each annotation for the respective website?
3- What happens when different heritage items are annotated on the same webpage?
4- Are there any other annotation media other than images, texts and video?
5- Will the users be able to comment on any type of annotations or just the questions?
6- Do we need to implement a notification system for the comments?
7- Should the users be able to add private annotations i.e. something that only they will see

**Comment by muatik** [comment]
What is the minimum information for each heritage item? 
A title, photo, location, source-URL etc? Concretely, is it allowed for a user to create a cultural heritage item by only providing the name of the item, let's say, "Turkish coffee"? Or at least one video or photo of Turkish coffee must be provided?

Should each cultural heritage item be associated a web resource? For instance, a user may want to create an item on the mobile web, without providing a web resource. Or a user may want to add only a bit information, such as location or time for a current cultural heritage without showing a source or a web resource.

Can users create cultural heritage items directly on the web and mobile application, without presenting source? "a user opens the mobile application, starts to fill the heritage form, provides title and upload a photo, finally submit it", is this allowed?

Let's say a user is reading an article about Mona Lisa on a website and wants to annotate a part of the article, which gives some location information about Mona Lisa. Through a web browser extension, the user should only type the heritage item by name and choose the right heritage item to be annotated?

If a user creates an annotation for Mona Lisa on a website a.com, can other users see the annotation while visiting the same website? 

Who can edit available information of a cultural heritage item? Are there any restrictions?

Should visitors able to see the revision list of a cultural heritage, in other words, should visitors be able to see the old version of the cultural heritage?

**Comment by isik5** [comment]
1- Do we need to implement a web app along with the Firefox Add-on?
2- Should we use categories or hashtags to identify the entity?
3- Admin Console?
4-Highlighter feature?
5- Collective editing for annotations?

**Comment by kartalerkoc** [comment]
1. Will the Firefox browser plugin enable a user to annotate any Web page on the internet?
     1.1 If so, will a random user be able to see all the annotations submitted by other plugin users on a particular Web page? (In "Genius" example, user can see other annotations after submitting their annotation)
2. Will there be both a Firefox plugin and a Web Application?
3. Is the number of languages to be used with the plugin (and Web App if there will be) is limited?
4. If there will be a Web App along with the Firefox plugin, will all of the annotations made in the other sites  be copied to the Web App? Otherwise, will the Web App just contain the annotations created within?
5. What does the phrase "media representations" involves in following project description sentence; "Heritage items need to have descriptions and support useful media representations". Does it include videos, photos, voice recordings and/or other forms?
6. While searching among annotations, will the users be able to search just the annotation titles or a keyword in annotation text?

**Comment by kartalerkoc** [comment]
The  [list](https://github.com/SWE574-RenameMe/heritago/wiki/Probing-Questions) has been prepared.
