### ISSUE TITLE
Recieving data from back-end to portfolio and search pages.

### ISSUE THREAD

**Issue by sanal-cem** [SWE574-RenameMe/swe574-CoolName#86]
To finish search, advanced search and portfolio pages, JSON like data should be received.

**Comment by muatik** [comment]
we should split this issue into two separate issues as they do not much relate each other.

#87

**Comment by sanal-cem** [comment]
I assumed that search data and portfolio data would have the same attributes except possible personal information in the portfolio page because both pages include heritage items.

**Comment by muatik** [comment]
then these two functionalities can be simply reduced to a single function: search. If you search by providing a user id for filtering it, then you can use the result as a portfolio.
