### ISSUE TITLE
Research the Web Annotation Data Model and Annotation tools

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#9]

**Comment by muatik** [comment]
I think that we should at least read the following pages: 
Data model: https://www.w3.org/TR/2017/PR-annotation-model-20170117/ 
Protocol: https://www.w3.org/TR/annotation-protocol/

**Comment by fkucuk** [comment]
and Vocabulary of course: [https://www.w3.org/TR/annotation-vocab/](https://www.w3.org/TR/annotation-vocab/)

**Comment by fkucuk** [comment]
the W3's implementation report on annotation protocol standards: [https://w3c.github.io/test-results/annotation-protocol/all.html](https://w3c.github.io/test-results/annotation-protocol/all.html)
It is actually a guide to test if your protocol is valid.
