### ISSUE TITLE
need to find a useful datepicker for BCE (before common era) and CE(common era) times while creating and searching for heritage items

### ISSUE THREAD

**Issue by kartalerkoc** [SWE574-RenameMe/swe574-CoolName#98]
@sanal-cem , we need to find a useful datepicker for BCE (before common era) and CE(common era) times while creating and searching for heritage items.

**Comment by kartalerkoc** [comment]
I have found [Any+Time DatePicker AJAX Calendar Widget](https://www.ama3.com/anytime/), a Javascript library and JQuery compatible datepicker, very useful. It has era selection just like we need. It includes a range of data selection varying from era selection (BCE - before common era and CE - common era) to years, day, hours and even seconds. What do you think @sanal-cem ?  
Edit: It is open-source! 👍

**Comment by isik5** [comment]
I was also going to suggest Any+Time but you can also take look at this one

https://github.com/angular-ui/bootstrap/tree/master/src/dateparser/docs

**Comment by sanal-cem** [comment]
Actually, I was trying to decide between some alternative date projections. Any+Time Datepicker accepts different date types and it works very easily only via Jquery and AJAX. It seems proper to our pages. I'm trying to integrate Any Time DatePicker into the discover.html page.

**Comment by sanal-cem** [comment]
Moreover, Javascript is enough to present minus dates. Below code could be used to give minus date into an <input element.
Easiest way to assign '-' dates via javascript.
```
<div class="input-group-content" >
        <input id="startDate" type="text" class="form-control">
        <label>Start Date</label>
</div>
<script type="javascript" >
    var startDate = new Date(-2015, 03, 25);
    $('#startDate').val(startDate.toDateString());
</script>
```

**Comment by kartalerkoc** [comment]
[Any+Time DatePicker AJAX Calendar Widget](https://www.ama3.com/anytime/) is being implemented on the pages and the results are satisfying.
